version: '3'

services:
  db:
    restart: always
    image: postgres
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
