# Generated by Django 2.0.7 on 2018-07-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20180708_2006'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmarks',
            field=models.ManyToManyField(to='feeds.Article'),
        ),
    ]
