# Generated by Django 2.0.7 on 2018-07-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
