# Generated by Django 2.0.7 on 2018-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20180708_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='guid',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
