# Generated by Django 2.0.7 on 2018-07-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20180708_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='guid',
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
