# Generated by Django 2.0.7 on 2018-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20180708_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
